# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generate_video_rcpp <- function(vertex_shader, fragment_shader, width, height, type, verbose, step, frames, filename) {
    .Call(`_shadr_generate_video_rcpp`, vertex_shader, fragment_shader, width, height, type, verbose, step, frames, filename)
}

open_window_rcpp <- function(vertex_shader, fragment_shader, width, height, type, verbose) {
    .Call(`_shadr_open_window_rcpp`, vertex_shader, fragment_shader, width, height, type, verbose)
}

open_window_image_rcpp <- function(vertex_shader, fragment_shader, width, height, verbose, r_layer, g_layer, b_layer) {
    .Call(`_shadr_open_window_image_rcpp`, vertex_shader, fragment_shader, width, height, verbose, r_layer, g_layer, b_layer)
}

