# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

open_window_two <- function(vertex_shader, fragment_shader, width, height) {
    .Call(`_shadr_open_window_two`, vertex_shader, fragment_shader, width, height)
}

